import {
  EventCategoryDTO,
  TemplateDTO,
  AnimationDTO,
  BackgroundDTO,
  DurationTierDTO,
} from "@/types";

export const MOCK_CATEGORIES: EventCategoryDTO[] = [
  {
    id: "cat_haldi",
    slug: "haldi",
    name: "Haldi & Gaye Holud",
    description: "Vibrant yellow tones, marigold florals, and turmeric smear reveals.",
    iconSvg: "sun",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "cat_wedding",
    slug: "wedding",
    name: "Royal Wedding",
    description: "Regal crimson, ivory damask, and physical wax-sealed envelopes.",
    iconSvg: "crown",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "cat_nikah",
    slug: "nikah",
    name: "Akhd & Nikah",
    description: "Sacred emerald greens, Islamic arabesque filigree, and serene blessings.",
    iconSvg: "scroll",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "cat_birthday",
    slug: "birthday",
    name: "Birthday Celebration",
    description: "Playful balloons, confetti bursts, and interactive candle-blow experiences.",
    iconSvg: "cake",
    sortOrder: 4,
    isActive: true,
  },
];

export const MOCK_TEMPLATES: TemplateDTO[] = [
  {
    id: "tpl_blush_envelope",
    slug: "soft-botanical-envelope",
    name: "Blush Botanical Envelope",
    description: "Delicate dusty rose paper, transparent foliage, and a centered gold monogram wax seal.",
    categoryId: "cat_wedding",
    price: 120.0,
    previewImageUrl: "/assets/previews/blush-botanical.webp",
    archetype: "soft_botanical",
    experienceType: "envelope",
    assetManifest: {
      backgroundAsset: "/assets/backgrounds/blush-warm/soft-cream-wash.svg",
      textureOverlay: "/assets/textures/handmade-fiber.webp",
      openingActor: {
        type: "envelope",
        assets: {
          primaryBase: "/assets/envelopes/blush-square/body.svg",
          animatedPart: "/assets/envelopes/blush-square/flap-top.svg",
          fastener: "/assets/seals/wax-monogram-gold.svg",
        },
        audioEffect: "/assets/audio/envelope-open.mp3",
      },
      framing: {
        borderStyle: "handdrawn_svg",
        frameAsset: "/assets/frames/handdrawn-minimal.svg",
        dividerAsset: "/assets/ribbons/satin-bow-minimal.svg",
      },
    },
    visualIdentity: {
      colorPalette: {
        id: "pal_blush",
        name: "Dusty Blush & Antique Gold",
        primary: "#8C4A52",
        secondary: "#D4AF37",
        accent: "#AA771C",
        background: "#FFFDF9",
        surface: "#F9F0EC",
        text: "#2C2623",
        mutedText: "#7C7267",
      },
      material: "handmade_paper",
      shadowTier: "elevated_card",
      typography: {
        id: "typo_editorial",
        titleFont: "Cinzel, serif",
        bodyFont: "Playfair Display, serif",
        bengaliFont: "Noto Serif Bengali, serif",
      },
    },
    openingConfig: {
      promptText: "Tap the seal to open your invitation",
      initialInteraction: "tap",
      soundAssetUrl: "/assets/audio/wax-seal-crack.mp3",
    },
    fieldsSchema: [
      { key: "groomName", label: "Groom's Name", type: "text", required: true, placeholder: "e.g. John" },
      { key: "brideName", label: "Bride's Name", type: "text", required: true, placeholder: "e.g. Lary" },
      { key: "eventDate", label: "Ceremony Date & Time", type: "datetime", required: true },
      { key: "venueName", label: "Venue Name", type: "text", required: true, placeholder: "e.g. Radisson Blu Grand Ballroom" },
      { key: "venueAddress", label: "Address", type: "textarea", required: true, placeholder: "Airport Road, Dhaka" },
      { key: "mapLink", label: "Google Maps URL", type: "text", required: false, placeholder: "https://maps.app.goo.gl/..." },
      { key: "sacredVerse", label: "Ceremonial Quote / Blessing", type: "text", required: false, placeholder: "Together with our families..." },
    ],
    styleConstraints: {
      allowedFontFamilies: ["Cinzel", "Playfair Display", "Noto Serif Bengali"],
      titleSize: { min: 24, max: 42, default: 32 },
      bodySize: { min: 13, max: 18, default: 15 },
    },
    isActive: true,
  },
  {
    id: "tpl_haldi_scratch",
    slug: "royal-haldi-multi-scratch",
    name: "Royal Haldi Multi-Scratch",
    description: "Interactive multi-zone reveal where guests swipe golden turmeric paste to reveal ceremony details.",
    categoryId: "cat_haldi",
    price: 150.0,
    previewImageUrl: "/assets/previews/midnight-gold.webp",
    archetype: "haldi_scratch",
    experienceType: "multi_scratch",
    assetManifest: {
      backgroundAsset: "/assets/backgrounds/festive-haldi/marigold-warm.svg",
      textureOverlay: "/assets/textures/parchment-grain.svg",
      openingActor: {
        type: "scratch_mask",
        assets: {},
      },
      framing: {
        borderStyle: "clean_border",
      },
    },
    visualIdentity: {
      colorPalette: {
        id: "pal_haldi",
        name: "Turmeric & Forest Olive",
        primary: "#E59E00",
        secondary: "#4A6B32",
        accent: "#D4AF37",
        background: "#FFFDF7",
        surface: "#FFF6D9",
        text: "#2C2623",
        mutedText: "#6E624A",
      },
      material: "turmeric_paste",
      shadowTier: "floating_ceremony",
      typography: {
        id: "typo_haldi",
        titleFont: "Playfair Display, serif",
        bodyFont: "sans-serif",
        bengaliFont: "Hind Siliguri, sans-serif",
      },
    },
    openingConfig: {
      promptText: "Swipe across the turmeric to reveal",
      initialInteraction: "scratch",
    },
    revealNodesConfig: [
      {
        nodeId: "node_bride",
        label: "Bride's Name",
        contentSlot: "brideName",
        interactionType: "scratch",
        scratchConfig: {
          coverTexture: "turmeric_smear",
          brushRadius: 28,
          completionThreshold: 0.6,
          particleBurstOnComplete: "turmeric_powder",
        },
      },
      {
        nodeId: "node_groom",
        label: "Groom's Name",
        contentSlot: "groomName",
        interactionType: "scratch",
        scratchConfig: {
          coverTexture: "turmeric_smear",
          brushRadius: 28,
          completionThreshold: 0.6,
          particleBurstOnComplete: "turmeric_powder",
        },
      },
      {
        nodeId: "node_date",
        label: "Auspicious Date",
        contentSlot: "eventDate",
        interactionType: "scratch",
        scratchConfig: {
          coverTexture: "gold_foil",
          brushRadius: 30,
          completionThreshold: 0.65,
          particleBurstOnComplete: "gold_glitter",
        },
      },
      {
        nodeId: "node_venue",
        label: "Venue & Map",
        contentSlot: "venueName",
        interactionType: "tap",
      },
    ],
    fieldsSchema: [
      { key: "brideName", label: "Bride's Name", type: "text", required: true, placeholder: "e.g. Nadia Islam" },
      { key: "groomName", label: "Groom's Name", type: "text", required: true, placeholder: "e.g. Fahim Rahman" },
      { key: "eventDate", label: "Haldi Night Date & Time", type: "datetime", required: true },
      { key: "venueName", label: "Venue Name", type: "text", required: true, placeholder: "e.g. Celebrations Convention Hall" },
      { key: "venueAddress", label: "Venue Address", type: "textarea", required: true, placeholder: "Dhanmondi, Dhaka" },
    ],
    styleConstraints: {
      allowedFontFamilies: ["Playfair Display", "Hind Siliguri", "Cinzel"],
      titleSize: { min: 26, max: 44, default: 34 },
      bodySize: { min: 14, max: 18, default: 16 },
    },
    isActive: true,
  },
  {
    id: "tpl_theatrical_curtain",
    slug: "royal-velvet-curtain",
    name: "Royal Theatrical Curtain",
    description: "Deep velvet crimson curtains parting gracefully to reveal a regal gold-bordered wedding decree.",
    categoryId: "cat_wedding",
    price: 180.0,
    previewImageUrl: "/assets/previews/heritage-crimson.webp",
    archetype: "theatrical_curtain",
    experienceType: "curtain",
    assetManifest: {
      backgroundAsset: "/assets/backgrounds/royal-crimson/velvet-dark.svg",
      textureOverlay: "/assets/textures/raw-silk-weave.svg",
      openingActor: {
        type: "curtain",
        assets: {
          leftCurtain: "/assets/curtains/royal-red/curtain-left.svg",
          rightCurtain: "/assets/curtains/royal-red/curtain-right.svg",
          valance: "/assets/curtains/royal-red/top-valance.svg",
        },
        audioEffect: "/assets/audio/curtain-part.mp3",
      },
      framing: {
        borderStyle: "arch_filigree",
        frameAsset: "/assets/frames/vintage-arch-filigree.svg",
      },
    },
    visualIdentity: {
      colorPalette: {
        id: "pal_curtain",
        name: "Imperial Velvet & Gold Leaf",
        primary: "#800020",
        secondary: "#D4AF37",
        accent: "#F9F0D0",
        background: "#4A050D",
        surface: "#FFFDF9",
        text: "#2A2624",
        mutedText: "#7A6858",
      },
      material: "raw_silk",
      shadowTier: "floating_ceremony",
      typography: {
        id: "typo_imperial",
        titleFont: "Cinzel, serif",
        bodyFont: "Playfair Display, serif",
      },
    },
    openingConfig: {
      promptText: "Slide curtains to reveal the ceremony",
      initialInteraction: "swipe",
      soundAssetUrl: "/assets/audio/curtain-part.mp3",
    },
    fieldsSchema: [
      { key: "groomName", label: "Groom's Name", type: "text", required: true },
      { key: "brideName", label: "Bride's Name", type: "text", required: true },
      { key: "eventDate", label: "Wedding Date", type: "datetime", required: true },
      { key: "venueName", label: "Venue", type: "text", required: true },
      { key: "venueAddress", label: "Full Address", type: "textarea", required: true },
    ],
    styleConstraints: {
      allowedFontFamilies: ["Cinzel", "Playfair Display"],
      titleSize: { min: 28, max: 48, default: 36 },
      bodySize: { min: 14, max: 18, default: 16 },
    },
    isActive: true,
  },
  {
    id: "tpl_minimal_editorial",
    slug: "clean-framed-editorial",
    name: "Clean Framed Minimal Editorial",
    description: "Understated luxury on handmade cotton paper, organic hand-drawn borders, and a dainty satin bow motif.",
    categoryId: "cat_wedding",
    price: 90.0,
    previewImageUrl: "/assets/previews/emerald-royal.webp",
    archetype: "minimal_editorial",
    experienceType: "envelope",
    assetManifest: {
      backgroundAsset: "/assets/backgrounds/blush-warm/pure-ivory.svg",
      textureOverlay: "/assets/textures/handmade-fiber.webp",
      openingActor: {
        type: "wax_seal_only",
        assets: {
          fastener: "/assets/seals/gold-foil-crested.svg",
        },
      },
      framing: {
        borderStyle: "handdrawn_svg",
        frameAsset: "/assets/frames/handdrawn-minimal.svg",
        dividerAsset: "/assets/ribbons/satin-bow-minimal.svg",
      },
    },
    visualIdentity: {
      colorPalette: {
        id: "pal_minimal",
        name: "Pure Ivory & Espresso",
        primary: "#2C2623",
        secondary: "#AA771C",
        accent: "#C5A059",
        background: "#FAF8F5",
        surface: "#FFFFFF",
        text: "#2C2623",
        mutedText: "#8C827A",
      },
      material: "handmade_paper",
      shadowTier: "soft_surface",
      typography: {
        id: "typo_minimal",
        titleFont: "Cinzel, serif",
        bodyFont: "system-ui, sans-serif",
      },
    },
    openingConfig: {
      promptText: "Tap to open",
      initialInteraction: "tap",
    },
    fieldsSchema: [
      { key: "brideName", label: "Bride's Name", type: "text", required: true },
      { key: "groomName", label: "Groom's Name", type: "text", required: true },
      { key: "eventDate", label: "Date & Time", type: "datetime", required: true },
      { key: "venueName", label: "Venue", type: "text", required: true },
      { key: "venueAddress", label: "Address", type: "textarea", required: true },
    ],
    styleConstraints: {
      allowedFontFamilies: ["Cinzel", "Playfair Display", "sans-serif"],
      titleSize: { min: 22, max: 36, default: 28 },
      bodySize: { min: 12, max: 16, default: 14 },
    },
    isActive: true,
  },
];

export const MOCK_ANIMATIONS: AnimationDTO[] = [
  {
    id: "anim_envelope",
    slug: "wax-seal-envelope-reveal",
    name: "Wax Seal & Envelope Unfold",
    description: "Physical wax seal cracks, envelope flap rotates upwards, and the card emerges.",
    price: 80.0,
    previewPosterUrl: "/assets/previews/anim-envelope.svg",
    pluginKey: "envelope_unfold",
    interactionType: "tap",
    soundEffectUrl: "/assets/audio/envelope-open.mp3",
    isActive: true,
  },
  {
    id: "anim_haldi_scratch",
    slug: "haldi-smear-scratch",
    name: "Haldi Smear & Gold Particle Reveal",
    description: "Finger swipe wipes away turmeric paste with gold glitter bursts.",
    price: 110.0,
    previewPosterUrl: "/assets/previews/anim-haldi.svg",
    pluginKey: "haldi_multi_scratch",
    interactionType: "scratch",
    soundEffectUrl: "/assets/audio/gentle-chime.mp3",
    isActive: true,
  },
  {
    id: "anim_curtain",
    slug: "theatrical-velvet-curtain",
    name: "Theatrical Velvet Curtain Reveal",
    description: "Heavy velvet panels ease open with soft fabric sound and ambient lighting.",
    price: 130.0,
    previewPosterUrl: "/assets/previews/anim-curtain.svg",
    pluginKey: "curtain_reveal",
    interactionType: "swipe",
    soundEffectUrl: "/assets/audio/curtain-part.mp3",
    isActive: true,
  },
];

export const MOCK_BACKGROUNDS: BackgroundDTO[] = [
  {
    id: "bg_blush_cream",
    name: "Dusty Blush Silk Parchment",
    previewUrl: "/assets/backgrounds/blush-warm/soft-cream-wash.svg",
    assetUrl: "/assets/backgrounds/blush-warm/soft-cream-wash.svg",
    theme: "blush_warm",
    price: 0.0,
    isPremium: false,
    isActive: true,
  },
  {
    id: "bg_haldi_marigold",
    name: "Festive Marigold & Sunlit Gold",
    previewUrl: "/assets/backgrounds/festive-haldi/marigold-warm.svg",
    assetUrl: "/assets/backgrounds/festive-haldi/marigold-warm.svg",
    theme: "festive_haldi",
    price: 0.0,
    isPremium: false,
    isActive: true,
  },
  {
    id: "bg_crimson_velvet",
    name: "Royal Crimson Damask",
    previewUrl: "/assets/backgrounds/royal-crimson/velvet-dark.svg",
    assetUrl: "/assets/backgrounds/royal-crimson/velvet-dark.svg",
    theme: "royal_crimson",
    price: 40.0,
    isPremium: true,
    isActive: true,
  },
];

export const MOCK_DURATION_TIERS: DurationTierDTO[] = [
  { id: "dur_15", days: 15, name: "15 Days (Standard)", price: 0.0, isDefault: true },
  { id: "dur_30", days: 30, name: "30 Days (Extended)", price: 30.0, isDefault: false },
  { id: "dur_60", days: 60, name: "60 Days (VIP Season)", price: 60.0, isDefault: false },
];
