import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function run() {
  const weddingCat = await prisma.eventCategory.findFirst({ where: { slug: 'wedding' } });
  if (!weddingCat) return;

  const newTemplates = [
    {
      slug: 'classic-editorial',
      name: 'Classic Editorial',
      description: 'Elegant centered composition with luxury frame and floral decoration.',
      categoryId: weddingCat.id,
      price: 1200.0,
      previewImageUrl: '/assets/Cards/card 1.png',
      archetype: 'editorial_classic',
      experienceType: 'dynamic_card',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 1.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'royal_gold' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'arch-portrait',
      name: 'Arch Portrait',
      description: 'Couple photo in arch frame with romantic typography.',
      categoryId: weddingCat.id,
      price: 1300.0,
      previewImageUrl: '/assets/Cards/card 2.png',
      archetype: 'arch_portrait',
      experienceType: 'dynamic_card',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 2.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'blush' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'botanical-luxury',
      name: 'Botanical Luxury',
      description: 'Floral frame with monogram and elegant typography.',
      categoryId: weddingCat.id,
      price: 1400.0,
      previewImageUrl: '/assets/Cards/card 3.png',
      archetype: 'botanical_luxury',
      experienceType: 'dynamic_card',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 3.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'sage' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'split-couple',
      name: 'Split Couple',
      description: 'Bride and groom side by side with decorative elements.',
      categoryId: weddingCat.id,
      price: 1500.0,
      previewImageUrl: '/assets/Cards/card 4.png',
      archetype: 'split_couple',
      experienceType: 'dynamic_card',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 4.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'festive' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'minimal-luxury',
      name: 'Minimal Luxury',
      description: 'Clean minimal design with monogram and elegant spacing.',
      categoryId: weddingCat.id,
      price: 1100.0,
      previewImageUrl: '/assets/Cards/card 5.png',
      archetype: 'minimal_editorial',
      experienceType: 'dynamic_card',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 5.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'minimal' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'cinematic',
      name: 'Cinematic Scene',
      description: 'Dramatic composition with atmospheric background.',
      categoryId: weddingCat.id,
      price: 1600.0,
      previewImageUrl: '/assets/Cards/card 2.png',
      archetype: 'cinematic',
      experienceType: 'dynamic_card',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 2.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'cinematic' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'romantic-center',
      name: 'Romantic Center',
      description: 'Soft floral design with centered romantic typography.',
      categoryId: weddingCat.id,
      price: 1200.0,
      previewImageUrl: '/assets/Cards/card 1.png',
      archetype: 'romantic_center',
      experienceType: 'dynamic_card',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 1.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'romantic' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'scroll-experience',
      name: 'Royal Heritage Scroll',
      description: 'Complete vertical storytelling experience with 8 multi-layered dynamic sections.',
      categoryId: weddingCat.id,
      price: 2000.0,
      previewImageUrl: '/assets/Cards/card 3.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 3.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'scroll' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'botanical-scroll',
      name: 'Botanical Emerald Scroll',
      description: 'Emerald and sage floral scroll experience with rich multi-event timeline.',
      categoryId: weddingCat.id,
      price: 2200.0,
      previewImageUrl: '/assets/Cards/card 5.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 5.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'sage' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'haldi-scroll',
      name: 'Golden Haldi Fiesta Scroll',
      description: 'Vibrant marigold yellow and golden celebration scroll designed specially for Gaye Holud, Mehendi and Sangeet.',
      categoryId: weddingCat.id,
      price: 1800.0,
      previewImageUrl: '/assets/Cards/card 4.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 4.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'gold' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'birthday-scroll',
      name: 'Celestial Birthday Glow Scroll',
      description: 'Enchanting midnight violet, gold confetti and birthday milestones with interactive wish counter.',
      categoryId: weddingCat.id,
      price: 1500.0,
      previewImageUrl: '/assets/Cards/card 1.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 1.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'violet' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'corporate-scroll',
      name: 'Corporate Prestige Summit Scroll',
      description: 'Executive deep navy and platinum scroll experience crafted for corporate galas and annual summits.',
      categoryId: weddingCat.id,
      price: 2500.0,
      previewImageUrl: '/assets/Cards/card 2.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 2.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'navy' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'velvet-scroll',
      name: 'Ruby Velvet Romance Scroll',
      description: 'Deep crimson velvet and champagne gold opulent scroll for grand wedding receptions.',
      categoryId: weddingCat.id,
      price: 2400.0,
      previewImageUrl: '/assets/Cards/card 5.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 5.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'crimson' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'floral-romance-scroll',
      name: 'Floral Romance Luxury Scroll',
      description: 'Enchanting floral animated scroll invitation with timeline itinerary and countdown.',
      categoryId: weddingCat.id,
      price: 2100.0,
      previewImageUrl: '/assets/Cards/card 1.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 1.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'rose' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'editorial-botanical-scroll',
      name: 'Editorial Botanical Scroll',
      description: 'Modern editorial typography with botanical framed portrait and minimalist story layout.',
      categoryId: weddingCat.id,
      price: 2200.0,
      previewImageUrl: '/assets/Cards/card 3.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 3.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'olive' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'cinematic-story-scroll',
      name: 'Cinematic Story Scroll',
      description: 'Dramatic full-screen visual storytelling with dark cinematic mood.',
      categoryId: weddingCat.id,
      price: 2600.0,
      previewImageUrl: '/assets/Cards/card 2.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 2.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'dark_gold' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'botanical-magazine-scroll',
      name: 'Botanical Magazine Scroll',
      description: 'High-fashion magazine layout with asymmetric botanical cutouts and earth tones.',
      categoryId: weddingCat.id,
      price: 2300.0,
      previewImageUrl: '/assets/Cards/card 5.png',
      archetype: 'scroll_story',
      experienceType: 'SCROLL',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 5.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'earth' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'royal-envelope',
      name: 'Royal Wax Seal Envelope',
      description: '3D wax seal break and royal invitation card slide ceremony.',
      categoryId: weddingCat.id,
      price: 1800.0,
      previewImageUrl: '/assets/Cards/card 1.png',
      archetype: 'envelope',
      experienceType: 'envelope',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 1.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'blush' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'theatrical-curtain',
      name: 'Theatrical Silk Curtain',
      description: 'Majestic red and gold velvet curtain parting reveal.',
      categoryId: weddingCat.id,
      price: 1900.0,
      previewImageUrl: '/assets/Cards/card 2.png',
      archetype: 'curtain',
      experienceType: 'curtain',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 2.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'royal_crimson' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    },
    {
      slug: 'haldi-scratch',
      name: 'Festive Multi-Scratch',
      description: 'Interactive golden foil scratch revealing wedding date, time and venue.',
      categoryId: weddingCat.id,
      price: 1700.0,
      previewImageUrl: '/assets/Cards/card 4.png',
      archetype: 'multi_scratch',
      experienceType: 'multi_scratch',
      assetManifest: JSON.stringify({ cardAsset: '/assets/Cards/card 4.png', decorations: [] }),
      visualIdentity: JSON.stringify({ theme: 'festive_haldi' }),
      openingConfig: JSON.stringify({}),
      layoutConfig: JSON.stringify({}),
      fieldsSchema: JSON.stringify({}),
      styleConstraints: JSON.stringify({}),
    }
  ];

  for (const t of newTemplates) {
    await prisma.template.upsert({
      where: { slug: t.slug },
      update: {
        name: t.name,
        price: t.price,
        previewImageUrl: t.previewImageUrl,
        experienceType: t.experienceType
      },
      create: t
    });
  }
  console.log('Templates successfully synced with database!');
}

run().catch(console.error).finally(() => prisma.$disconnect());
